project_id = "uaqnolatlyxiluypzrpr"

[functions.auth-login]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.reset-password]
verify_jwt = true

[functions.claude-proxy]
verify_jwt = false

[functions.manage-api-keys]
verify_jwt = false