// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaqnolatlyxiluypzrpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhcW5vbGF0bHl4aWx1eXB6cnByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjY5MDMsImV4cCI6MjA3MjQwMjkwM30.bwbDemlkRtgn6dMUZ4KC4C4lR8wtM2QFN32512lgUv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});